Project/JobHorizon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHorizon.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/JobHorizon/Controllers/RegistrationController.cs
using JobHorizon.Interface;
using JobHorizon.Models;
using JobHorizon.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHorizon.Controllers
{
    public class RegistrationController : Controller
    {
        
        IRepository<User> userRepo = new UserRepository();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(User u, HttpPostedFileBase file)
        {
            u.Rating = 0;
            u.Account_Status = "Active";
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images"),
                                               Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    TempData["Message"] = "File uploaded successfully";
                    u.ProfileImage = file.FileName;
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "ERROR:" + ex.Message.ToString();
                }
            }
            userRepo.Insert(u);
            return RedirectToAction("Index", "Login");
        }
    }
}

Project/JobHorizon/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/style/designFile.css" rel="stylesheet" type="text/css">
    <title>Job Horizon</title>
</head>
<body>
    <div class="header">
        <h1> &nbsp &nbsp &nbsp Job Horizon </h1>
        <h3> &nbsp &nbsp &nbsp  &nbsp &nbsp An online portal to connect people </h3>
        
        <p class="linkTable">
            @Html.ActionLink("Login", "index", "Login")   ||   @Html.ActionLink("Register", "index", "Registration")
        </p>
    </div>
    <br><br><br><br>
    <div align="center">
        <p style="text-align:justify;width:60%;">
            <b>Job Horizon </b> is a platform to connect people in their needs. There are always multiple services that we are in needs but cann't find out the right person we are looking for, the problem gets much longer when we are actually a very new person to unknown locations. It is very difficult to find out a way where to look for or seek the right work person for your job.<br/><br />
            Well in that case <b>Job Horizon </b> can bring the solution up to you. You can post a job from anywhere you want for, as well as can find out previous people's experience on getting the job finished from our job seekers. Moreover you can have a look over the <b>ratings of our job seekers profile</b> to make your decision more quickly and correct to find out the right person always.<br/><br />
            <b>Please feel free to connect anytime for online services.</b> More then a hundred of Job Holders are currently waiting for your request to get job done for yours. Thank you for choosing JobHorizon.<br/><br />
            Contact:<br/>
            admin@jobhorizon.com<br />
            +88-025-34236<br />
        </p>
    </div>
</body>
</html>