Project/JobHorizon/Controllers/DashboardController.cs
using JobHorizon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHorizon.Controllers
{
    public class DashboardController : Controller
    {
        JobHorizonContext context = new JobHorizonContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Statistics()
        {
            try
            {
                ViewBag.NoOfUser = context.Set<User>().Count();
                ViewBag.NoOfJobs = context.Set<JobList>().Count();
                return View();
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

Project/JobHorizon/Controllers/JobHistoryController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using JobHorizon.Models;
using JobHorizon.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHorizon.Controllers
{
    public class JobHistoryController : Controller
    {
        Document doc;
        MemoryStream mem = new MemoryStream();

        JobListRepository JobListRepo = new JobListRepository();
        JobHistoryRepository JobHistoryRepo = new JobHistoryRepository();
        BidRepository BidRepo = new BidRepository();
        MessegeRepository msgRepo = new MessegeRepository();

        public ActionResult Index()
        {
            if(Session["UserType"].ToString() == "Admin")
            {
                return View(JobHistoryRepo.GetAll());
            }
            else if(Session["UserType"].ToString() == "Customer")
            {
                return View(JobHistoryRepo.GetApprovedJob(Int32.Parse(Session["UserId"].ToString())));
            }
            else
            {
                return View(JobHistoryRepo.GetApprovedJobByType(Session["WorkType"].ToString()));
            }
        }

        public ActionResult Completed()
        {
            return View(JobHistoryRepo.GetHistoryById(Convert.ToInt32(Session["UserId"])));
        }
        public ActionResult Approve()
        {
            var j = new JobHistory();
            int BidId = Int32.Parse(Session["BidId"].ToString());
            //job approve in jobhistory table
            var JobApprove = BidRepo.Get(BidId);

            j.JobId = JobApprove.JobId;
            j.BitBy = JobApprove.BidBy;
            j.Status = "Pending";
            j.Rating = 0;


            //return Content(Bid.ToString());
            JobHistoryRepo.Insert(j);
            // Modify in joblist table
            var joblist = JobListRepo.Get(JobApprove.JobId);
            joblist.Status = "Pending";
            JobListRepo.Update(joblist);

            ////Add to messege table two way ato communication
            //var m = new Messege();
            //m.SenderId = postedBy;
            //m.ReceiverId = Bid;
            //m.Messege1 = "Hello Mr/Ms " + j.User.Name+" I Have appointed you for this job";
            //m.CreatedAt = DateTime.Now;
            //msgRepo.Insert(m);

            //var m2 = new Messege();
            //m2.SenderId = Bid;
            //m2.ReceiverId = postedBy; 
            //m2.Messege1 = "Lets Discuss About the Job in details";
            //m2.CreatedAt = DateTime.Now;
            //msgRepo.Insert(m);

            return RedirectToAction("Index","JobList");
        }
        [HttpGet]
        public ActionResult Finished(int id)
        {
            Session["HistoryId"] = id;
            return View();
        }
        [HttpPost]
        public ActionResult Finished(JobHistory j)
        {
            
            var job = JobHistoryRepo.Get(Int32.Parse(Session["HistoryId"].ToString()));
            job.Rating = j.Rating;
            job.Status = "Finished";
            JobHistoryRepo.Update(job);

            return RedirectToAction("Index", "JobList");
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            JobHistoryRepo.Delete(id);
            return RedirectToAction("Index");
        }





        [HttpGet, ActionName("Download")]
        public ActionResult CreateFile()
        {
            //List<object> history = JobHistoryRepo.HistoryList(Convert.ToInt32(Session["UserId"]));
            byte[] abytes = this.preparePDF();
            return File(abytes, "application/pdf");
        }

        public byte[] preparePDF()
        {
            string str2 = JobHistoryRepo.HistoryList(Convert.ToInt32(Session["UserId"]));

            IList<string> newlist = new List<string>();
            newlist.Add("Haay");
            newlist.Add("there jami");
            Paragraph para = new Paragraph();
            Chunk data = new Chunk();

            //string str2 = "\n";
            //for (int i = 0; i < newlist.Count; i++)
            //{
            //    str2 = newlist[i].ToString();
            //    data.Append(str2 + Environment.NewLine);
            //    para.Add(new Chunk(str2));
            //    para.Add(Chunk.NEWLINE);
            //}

            para.Add(new Chunk(str2));

            string path = Server.MapPath("PDFs");
            Chunk hello = new Chunk("Hye There");
            doc = new Document(PageSize.A4, 0f, 0f, 0f, 0f);
            doc.SetPageSize(PageSize.A4);
            doc.SetMargins(20f, 20f, 20f, 20f);

            PdfWriter.GetInstance(doc, new FileStream(path + "/Report.pdf", FileMode.Create));
            PdfWriter.GetInstance(doc, mem);
            doc.Open();
            doc.Add(para);
            doc.Close();
            return mem.ToArray();
        }
    }
}

Project/JobHorizon/Controllers/UserController.cs
using JobHorizon.Interface;
using JobHorizon.Models;
using JobHorizon.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobHorizon.Controllers
{
    public class UserController : Controller
    {
        IRepository<User> userRepo = new UserRepository();

        public ActionResult UserCheck()
        {
            if (Session["UserType"].ToString() == "Admin")
            {
                return RedirectToAction("Index", "DashBoard");
            }
            else
            {
                return RedirectToAction("Index", "JobList");
            }

        }
        public ActionResult Index()
        {
                return View(userRepo.GetAll());
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(userRepo.Get(id));

        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(User u, HttpPostedFileBase file)
        {
            u.Rating = 0;
            u.Account_Status = "Active";
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Images"),
                                               Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    TempData["Message"] = "File uploaded successfully";
                    u.ProfileImage = file.FileName;
                }
                catch (Exception ex)
                {
                    TempData["Message"] = "ERROR:" + ex.Message.ToString();
                }
            }
            userRepo.Insert(u);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(userRepo.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(User u)
        {
            userRepo.Update(u);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(userRepo.Get(id));
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            userRepo.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
        public ActionResult MessegeList()
        {
            return View(userRepo.GetAll());
        }
        public ActionResult Messege(int id)
        {
            Session["ContactId"] = id;
            //return Content(id.ToString());
            return RedirectToAction("Index","Messege");
        }
        public ActionResult GetConnectedPeople(int id)
        {
            Session["ContactId"] = id;
            //return Content(id.ToString());
            return RedirectToAction("Index", "Messege");
        }
        [HttpGet]
        public ActionResult Forum()
        {
            return RedirectToAction("Index", "Forum");
        }
    }
}

Project/JobHorizon/Views/Dashboard/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/style/designFile.css" rel="stylesheet" type="text/css">
    <title>Admin Dashboard Page - Job Horizon</title>
</head>
<body>
    <div class="header">
        <h1> &nbsp &nbsp &nbsp Job Horizon - Admin Panel </h1>
        <p class="linkTable">
            @Html.ActionLink("Home", "UserCheck", "User")
            ||
            @Html.ActionLink("Logout", "Logout", "User")
        </p>
    </div>
       
        <div style="margin-top:50px; text-align:center;">
            <center>
                <table>
                    <tr>
                        <td>
                            @Html.ActionLink("Users", "Index", "User")<br />
                        </td>
                        <td>
                            @Html.ActionLink("Active Job Posts", "Index", "JobList")<br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Running/Finished Job Posts", "index", "JobHistory")<br />
                        </td>
                        <td>
                            @Html.ActionLink("View Forum", "Forum", "User")<br />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("Messeges", "MessegeList", "Messege")<br />
                        </td>
                        <td>
                            @Html.ActionLink("Statistics", "Statistics", "Dashboard")<br />
                        </td>
                    </tr>
                </table>
            </center>
            </div>
     
</body>
</html>

Project/JobHorizon/Views/Dashboard/Statistics.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Statistics</title>
</head>
<body>
    <div align="center">
        <h2>Statistics</h2>
        <hr />

        <div>
            Total No of Users: @ViewBag.NoOfUser
        </div>
        <div>
            Total No of Jobs: @ViewBag.NoOfJobs
        </div>
    </div>
</body>
</html>